// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern ap_uint<20> AESL_WRAP_simpleALU (
ap_uint<20> ina,
ap_uint<20> inb,
ap_uint<1> op);
